Add accessible text content
wearerequired/rest-likes pull request #148
Opened 2024-08-20 18:04 UTC by krokodok

For #76, inspired by https://github.com/wearerequired/swisscom-magazine/issues/1256.

https://github.com/wearerequired/rest-likes/compare/master...feature/accessible-text-content#diff-3aa09978cb18aff029d3dd6535a2b9ee0a8c4df561ceae68517deb6bac6ffa7aR182-R195

https://github.com/wearerequired/rest-likes/compare/master...feature/accessible-text-content#diff-3aa09978cb18aff029d3dd6535a2b9ee0a8c4df561ceae68517deb6bac6ffa7aR329-R342

I wanted to include these strings as filters, the same as here: https://github.com/wearerequired/rest-likes/blob/feature/accessible-text-content/inc/Plugin.php#L155-L167

But because I don't know the `count` yet in the Php definition, I have to translate the string during runtime.

2024-08-22 07:10 UTC, ocean90 requested changes

2024-08-22 07:10 UTC, ocean90 commented on inc/Plugin.php
> +				],
Let's remove this since we can't provide the actual strings here.

2024-08-22 07:10 UTC, ocean90 commented on js/src/index.js
> +				sprintf( objectTypeData.html.screen_reader_text, likeButtonScreenReaderText ); // eslint-disable-line @wordpress/valid-sprintf
Use `document.createElement()` with `.textContent` for the text.

2024-08-27 10:23 UTC, ocean90 requested changes

2024-08-27 10:23 UTC, ocean90 commented on inc/Controller.php
> +			);
```suggestion
			$likes_text = __( 'One like', 'rest-likes' );
```

Die Überprüfung auf 1 erlaubt uns extra einen anderen Text ohne Platzhalter zu werden. Das sollte überall geändert werden.

2024-08-27 10:23 UTC, ocean90 commented on inc/Controller.php
> +				/* translators: $s = number of likes */
```suggestion
				/* translators: %s: Number of likes */
```

Das sollte ebenfalls überall geändert werden.

2024-08-27 10:50 UTC, krokodok commented on inc/Controller.php
> +			);
Schau mal hier: https://github.com/wearerequired/rest-likes/pull/148/commits/6aa53e65aa4035482acfc95be38fc7b30c32e051

2024-08-27 10:50 UTC, krokodok commented on inc/Controller.php
> +				/* translators: $s = number of likes */
Siehe: https://github.com/wearerequired/rest-likes/pull/148/commits/6aa53e65aa4035482acfc95be38fc7b30c32e051

2024-08-27 11:45 UTC, ocean90 approved these changes

2024-08-27 13:32 UTC, merged